{{- if and .Values.rbac.create .Values.exclusionConfig.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vpa-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa-provisioner.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vpa-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vpa-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "vpa-provisioner.fullname" .) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
