apiVersion: v2
name: vpa-provisioner
description: Automatically provisions VerticalPodAutoscaler objects for Deployments and StatefulSets
type: application
version: 0.1.0
appVersion: "0.1.0"
annotations:
  artifacthub.io/license: Apache-2.0
keywords:
  - vpa
  - autoscaling
  - rightsizing
home: https://github.com/runwhen-contrib/vpa-provisioner
sources:
  - https://github.com/runwhen-contrib/vpa-provisioner
maintainers:
  - name: RunWhen
    url: https://runwhen.com
